"""Public boundary for bounded Full Model v0.1 corrective-action proposals."""

from .domain import (
    ACTION_RECORD_VERSION,
    ACTION_RULE_REF,
    PROCESS_REASSESSMENT_CONTRACT_REF,
    VERIFICATION_RULE_REF,
    ActionCreatorSource,
    ActionRef,
    ActionTargetRequirement,
    CorrectiveAction,
    CorrectiveActionContext,
    CorrectiveActionExpectedOutcome,
    CorrectiveActionId,
    CorrectiveActionKind,
    CorrectiveActionNonOptimalityClaim,
    CorrectiveActionProvenance,
    CorrectiveActionRationale,
    CorrectiveActionReason,
    CorrectiveActionResolution,
    CorrectiveActionResolutionId,
    CorrectiveActionResolutionProvenance,
    CorrectiveActionStatus,
    ProposedChangeKind,
    RequirementLineageId,
)
from .service import propose_corrective_action

__all__ = [
    "ACTION_RECORD_VERSION",
    "ACTION_RULE_REF",
    "PROCESS_REASSESSMENT_CONTRACT_REF",
    "VERIFICATION_RULE_REF",
    "ActionCreatorSource",
    "ActionRef",
    "ActionTargetRequirement",
    "CorrectiveAction",
    "CorrectiveActionContext",
    "CorrectiveActionExpectedOutcome",
    "CorrectiveActionId",
    "CorrectiveActionKind",
    "CorrectiveActionNonOptimalityClaim",
    "CorrectiveActionProvenance",
    "CorrectiveActionRationale",
    "CorrectiveActionReason",
    "CorrectiveActionResolution",
    "CorrectiveActionResolutionId",
    "CorrectiveActionResolutionProvenance",
    "CorrectiveActionStatus",
    "ProposedChangeKind",
    "RequirementLineageId",
    "propose_corrective_action",
]
